#!/usr/bin/env bash

jobEnvFile=$1

if [[ "${2^^}" == "DRYRUN" ]]; then
    dryRun=$2
fi

configDir=$(dirname "$jobEnvFile")
cpEnvFile="$configDir/controlplane.env"

if [ -z "$jobEnvFile" ]; then
    echo "Unable to find job file: '$jobEnvFile'"
    exit 1
elif [ -z "$cpEnvFile" ]; then
    echo "Unable to find Control Plan config file: '$cpEnvFile'"
    exit 1
fi

dockercmd="docker run --rm ${dryRun:+ -e REPO_CRAWLER_DRY_RUN=true} --env-file \"$jobEnvFile\" --env-file \"$cpEnvFile\" us-docker.pkg.dev/cyralinc/cyral-repo-crawler/cyral-repo-crawler:v0.3.0"
echo "Invoking job: $dockercmd"
if ! sudoOutput=$(eval sudo -n "$dockercmd" 2>&1); then
    if ! stdOutput=$(eval "$dockercmd" 2>&1); then
        echo "FAILED to invoke crawler job!"
        echo "Sudo Attempt: $sudoOutput"
        echo "Standard Attempt: $stdOutput"
    else
        output="$stdOutput"
    fi
else
output="$sudoOutput"
fi
echo "$output"